# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Terraform Lab Docker Hub Connection'
        repository: 'aliabdulhussein/app-api'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
- stage: Provision
  displayName: "Terraform Provision on Azure"
  dependsOn: Build
  jobs:
    - job: Provision
      displayName: "Provision Container INstance"
      pool:
        vmImage: ubuntu-latest
      variables:
      - group: TerraformEnvVariables
      steps:
        - script: |
            set -e

            terraform init -input=false
            terraform apply -input=false -auto-approve
          name: "RunTerraform"
          displayName: "Run Terraform"
          env:
            ARM_CLIENT_ID: $(ARM_CLIENT_ID)
            ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
            ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
            ARM_TENANT_ID: $(ARM_TENANT_ID)
            TF_VAR_imagebuild: $(tag)
            


      


